# Generated by Django 4.2.30 on 2026-06-19 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_alter_stockmovement_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Stock Movements'},
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='sm_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 0)), name='sm_non_negative_rate'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('movement_type', 'Inward'), _negated=True), models.Q(('from_warehouse__isnull', True), ('to_warehouse__isnull', False)), _connector='OR'), name='sm_inward_warehouses'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('movement_type', 'Outward'), _negated=True), models.Q(('from_warehouse__isnull', False), ('to_warehouse__isnull', True)), _connector='OR'), name='sm_outward_warehouses'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('movement_type', 'Transfer'), _negated=True), models.Q(('from_warehouse__isnull', False), ('to_warehouse__isnull', False), models.Q(('from_warehouse', models.F('to_warehouse')), _negated=True)), _connector='OR'), name='sm_transfer_warehouses'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('movement_type', 'Adjustment'), _negated=True), ('from_warehouse__isnull', False), ('to_warehouse__isnull', False), _connector='OR'), name='sm_adjustment_requires_warehouse'),
        ),
    ]
