# Generated by Django 4.2.30 on 2026-07-10 08:05

from django.db import migrations, models


def backfill_item_codes(apps, schema_editor):
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    for item in InventoryItem.objects.filter(item_code__in=['', None]).order_by('id'):
        item.item_code = f'ITEM-{item.id:04d}'
        item.save(update_fields=['item_code'])


def seed_categories(apps, schema_editor):
    InventoryCategory = apps.get_model('inventory', 'InventoryCategory')
    defaults = [
        ('Solar Panel', 'PV modules and panels'),
        ('Inverter', 'Grid-tie and hybrid inverters'),
        ('Battery', 'Storage batteries'),
        ('Structure', 'Mounting structures and rails'),
        ('Cable & Wire', 'DC/AC cables and wiring'),
        ('ACDB/DCDB', 'Distribution boxes'),
        ('Steel', 'Angle, channel, sheet, pipe etc.'),
        ('Hardware', 'Nuts, bolts, fasteners, consumables'),
        ('Other', 'Miscellaneous items'),
    ]
    for name, description in defaults:
        InventoryCategory.objects.get_or_create(name=name, defaults={'description': description})


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.RunPython(backfill_item_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Purchase Invoice', 'Purchase Invoice'), ('Purchase Challan', 'Purchase Challan'), ('Sell Challan', 'Sell Challan'), ('Jobs', 'Jobs'), ('Opening Stock', 'Opening Stock')], default='Manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('Nos', 'Nos'), ('pcs', 'pcs'), ('Meter', 'Meter'), ('Kg', 'Kg'), ('kg', 'kg'), ('Ltr', 'Ltr'), ('ltr', 'ltr'), ('Roll', 'Roll'), ('Set', 'Set')], default='Nos', max_length=20),
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
