# Generated by Django 4.2.30 on 2026-06-18 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_alter_stockmovement_created_by'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, default='Nos', max_length=20)),
                ('required_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issued_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consumed_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('Site Survey', 'Site Survey'), ('Installation', 'Installation')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('is_checked', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['phase', 'category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], default='Pending', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sequence', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inverter_brand', models.CharField(blank=True, max_length=100)),
                ('inverter_model', models.CharField(blank=True, max_length=100)),
                ('inverter_capacity_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('panel_brand', models.CharField(blank=True, max_length=100)),
                ('panel_model', models.CharField(blank=True, max_length=100)),
                ('panel_wattage_w', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('panel_count', models.IntegerField(blank=True, null=True)),
                ('string_count', models.IntegerField(blank=True, null=True)),
                ('protection_devices', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(blank=True, max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('survey_date', models.DateField(blank=True, null=True)),
                ('building_type', models.CharField(blank=True, max_length=100)),
                ('floor_count', models.CharField(blank=True, max_length=20)),
                ('roof_type', models.CharField(blank=True, max_length=100)),
                ('site_details', models.JSONField(blank=True, default=list)),
                ('roof_details', models.JSONField(blank=True, default=list)),
                ('electrical_details', models.JSONField(blank=True, default=list)),
                ('roof_stats', models.JSONField(blank=True, default=list)),
                ('feasibility', models.CharField(blank=True, choices=[('Feasible', 'Feasible'), ('Feasible with Conditions', 'Feasible with Conditions'), ('Not Feasible', 'Not Feasible')], max_length=30)),
                ('summary_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='projectdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='projectexpense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Work Orders'},
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='activity_type',
            field=models.CharField(choices=[('Site Survey', 'Site Survey'), ('Material Delivery', 'Material Delivery'), ('Installation', 'Installation'), ('Testing', 'Testing'), ('Commissioning', 'Commissioning'), ('Safety', 'Safety'), ('Other', 'Other')], default='Other', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(fields=('project', 'task'), name='unique_task_per_project'),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_survey', to='projects.project'),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='surveyed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectteammember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectteammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsystemconfig',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_config', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.projectmilestone'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectchecklistitem',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectchecklistitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='projects.project'),
        ),
        migrations.AddField(
            model_name='installationmaterial',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_uses', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='installationmaterial',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_materials', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='projectteammember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_member_per_project'),
        ),
    ]
