# Generated by Django 4.2.30 on 2026-06-19 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_installationmaterial_projectchecklistitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS')], default='Bank Transfer', max_length=30)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_payments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
