# Generated by Django 4.2.30 on 2026-06-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_project_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/%Y/%m/'),
        ),
    ]
