# Generated by Django 4.2.30 on 2026-06-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteammember',
            name='access_level',
            field=models.CharField(choices=[('full_access', 'Full Access'), ('edit_access', 'Edit Access'), ('view_only', 'View Only')], default='view_only', max_length=20),
        ),
    ]
