# Generated by Django 4.2.30 on 2026-07-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_consumer_number_project_discom_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('items', models.CharField(blank=True, default='', max_length=50)),
                ('uom', models.CharField(default='Nos', max_length=20)),
                ('planned_qty', models.CharField(blank=True, default='', max_length=50)),
                ('planned_value', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Partially Completed', 'Partially Completed'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], default='Not Started', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_plans', to='projects.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
