# Generated by Django 4.2.30 on 2026-07-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_add_material_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteammember',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Site', 'On Site'), ('Off Site', 'Off Site'), ('On Leave', 'On Leave')], default='Active', max_length=20),
        ),
    ]
