# Generated by Django 4.2.30 on 2026-07-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_team_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCDApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=100)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('discom', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Process', 'Under Process'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('assigned_employee', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cd_applications', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubCDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('Electricity Bill', 'Electricity Bill'), ('Aadhaar', 'Aadhaar'), ('PAN', 'PAN'), ('Approval Letter', 'Approval Letter'), ('Other', 'Other')], default='Other', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='sub_cd_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sub_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.subcdapplication')),
            ],
        ),
    ]
