# Generated by Django 4.2.30 on 2026-07-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_add_expense_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexpense',
            name='paid_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectexpensedocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subsidyapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_applications', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='subsidydocument',
            name='file',
            field=models.FileField(upload_to='subsidy_docs/%Y/%m/'),
        ),
    ]
