# Generated by Django 4.2.30 on 2026-07-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_add_project_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesurvey',
            name='latitude',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='longitude',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
