# Generated by Django 4.2.30 on 2026-07-07 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_sitesurvey_latitude_sitesurvey_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesurvey',
            name='ac_cable_length_approx',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='ac_cable_route',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='approx_plant_capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='conduit_length_approx',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='conduit_route_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='connection_point_after_commissioning',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='dc_cable_length_approx',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='dc_cable_route',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='earthing_count',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='earthing_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='earthing_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='earthing_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='earthing_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='existing_mcb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='future_expansion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='inverter_distance_from_roof',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='inverter_location_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='inverter_mounting',
            field=models.CharField(blank=True, choices=[('Wall Mounted', 'Wall Mounted'), ('Floor Mounted', 'Floor Mounted')], max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='inverter_placement',
            field=models.CharField(blank=True, choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='meter_capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='meter_phase',
            field=models.CharField(blank=True, choices=[('Single Phase', 'Single Phase'), ('Three Phase', 'Three Phase')], max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='meter_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='meter_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='module_orientation',
            field=models.CharField(blank=True, choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape')], max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='obstacle_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='roof_height_ft',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='roof_length_ft',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='roof_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='roof_width_ft',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='safety_all_photos_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='safety_cable_route_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='safety_customer_approval_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='safety_earthing_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='safety_gps_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='safety_inverter_location_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='safety_meter_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='safety_roof_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='safety_shadow_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='safety_tank_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='shadow_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='structure_columns',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='structure_rows',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='tilt_angle',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='tree_nearby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='water_tank_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesurvey',
            name='roof_type',
            field=models.CharField(blank=True, choices=[('RCC', 'RCC'), ('Tin Shed', 'Tin Shed'), ('Metal Roof', 'Metal Roof'), ('Ground Mount', 'Ground Mount')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesurvey',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SiteSurveyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('North Side', 'North Side'), ('South Side', 'South Side'), ('East Side', 'East Side'), ('West Side', 'West Side'), ('Overall Roof', 'Overall Roof'), ('Roof Close-up', 'Roof Close-up'), ('Water Tank', 'Water Tank'), ('Obstacle', 'Obstacle'), ('Drone Photo', 'Drone Photo'), ('Earthing Location', 'Earthing Location'), ('Inverter Location', 'Inverter Location'), ('Meter', 'Meter'), ('Cable Route', 'Cable Route')], max_length=30)),
                ('image', models.ImageField(upload_to='site_survey_photos/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.sitesurvey')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_site_survey_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('survey', 'slot')},
            },
        ),
    ]
