# Generated by Django 4.2.30 on 2026-07-07 11:49

from django.db import migrations


def migrate_draft_to_in_progress(apps, schema_editor):
    # Old status set was Draft/Completed; new set is Pending/In Progress/Completed.
    # A saved-but-not-completed survey maps to "In Progress" (data exists),
    # whereas "Pending" now means no survey has been started at all.
    SiteSurvey = apps.get_model('projects', 'SiteSurvey')
    SiteSurvey.objects.filter(status='Draft').update(status='In Progress')


def reverse_migration(apps, schema_editor):
    SiteSurvey = apps.get_model('projects', 'SiteSurvey')
    SiteSurvey.objects.filter(status='In Progress').update(status='Draft')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_sitesurvey_ac_cable_length_approx_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_draft_to_in_progress, reverse_migration),
    ]
