# Generated by Django 4.2.30 on 2026-07-08 07:07

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_migrate_draft_survey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesurveyphoto',
            name='image',
            field=models.ImageField(upload_to=apps.projects.models.site_survey_photo_upload_path),
        ),
    ]
