# Generated by Django 4.2.30 on 2026-07-10 06:20

import apps.projects.models
import django.core.validators
from django.db import migrations, models
import malwa_solar.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_sitesurveyphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), malwa_solar.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='projectapprovaldocument',
            name='file',
            field=models.FileField(upload_to='approval_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx']), malwa_solar.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(upload_to='project_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx']), malwa_solar.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='projectexpensedocument',
            name='file',
            field=models.FileField(upload_to='expense_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx']), malwa_solar.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='sitesurveyphoto',
            name='image',
            field=models.ImageField(upload_to=apps.projects.models.site_survey_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), malwa_solar.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='subsidydocument',
            name='file',
            field=models.FileField(upload_to='subsidy_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx']), malwa_solar.validators.validate_upload_size]),
        ),
    ]
