# Generated by Django 4.2.30 on 2026-07-10 06:42
# Hand-edited: the auto-generated `assigned_employee` AlterField (CharField ->
# ForeignKey) would issue a raw column-type change that Postgres can't apply
# when existing rows hold non-numeric free text (BUG-041) — that would fail
# the migration outright on any environment with real data. Replaced with a
# rename/add/data-migrate/remove sequence that does a best-effort match by
# employee name and leaves unmatched rows null instead of erroring.

from django.db import migrations, models
import django.db.models.deletion


def migrate_assigned_employee_text_to_fk(apps, schema_editor):
    SubsidyApplication = apps.get_model('projects', 'SubsidyApplication')
    Employee = apps.get_model('workforce', 'Employee')

    matched = 0
    unmatched = 0
    for row in SubsidyApplication.objects.exclude(assigned_employee_legacy='').iterator():
        name = (row.assigned_employee_legacy or '').strip()
        if not name:
            continue
        employee = Employee.objects.filter(name__iexact=name).first()
        if employee:
            row.assigned_employee_id = employee.id
            row.save(update_fields=['assigned_employee'])
            matched += 1
        else:
            unmatched += 1
    if matched or unmatched:
        print(
            f'  [migrate assigned_employee] {matched} row(s) matched to an Employee by name, '
            f'{unmatched} row(s) left null (no matching Employee.name).'
        )


def noop_reverse(apps, schema_editor):
    # Not reversible in a meaningful way (we'd have to reconstruct free text
    # from the FK); reversing this migration just leaves the legacy text
    # field empty, which is acceptable for a down-migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_employeeidcounter_alter_employee_department'),
        ('projects', '0019_alter_project_project_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectpayment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='projects.project'),
        ),
        # Step 1: keep the old free-text values under a temporary name.
        migrations.RenameField(
            model_name='subsidyapplication',
            old_name='assigned_employee',
            new_name='assigned_employee_legacy',
        ),
        # Step 2: add the real FK field alongside it.
        migrations.AddField(
            model_name='subsidyapplication',
            name='assigned_employee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='subsidy_applications', to='workforce.employee',
            ),
        ),
        # Step 3: best-effort case-insensitive name match, row by row.
        migrations.RunPython(migrate_assigned_employee_text_to_fk, noop_reverse),
        # Step 4: drop the temporary free-text field now that the FK is populated.
        migrations.RemoveField(
            model_name='subsidyapplication',
            name='assigned_employee_legacy',
        ),
    ]
