# Generated by Django 4.2.30 on 2026-07-18 11:34

import django.core.validators
from django.db import migrations, models
import malwa_solar.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_sequencecounter_alter_projectexpense_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesurvey',
            name='ac_cable_entry_point',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='additional_observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='average_monthly_bill',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='back_leg_height_ft',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='cable_route_distance_m',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='capacity_required_kw',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='customer_confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='customer_confirmation_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='existing_connection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='extend_sanction_load_kw',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='front_leg_height_ft',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='ivrs_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='la_wire_length_m',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='last_termination_point',
            field=models.CharField(blank=True, choices=[('MCB', 'MCB'), ('Cutout', 'Cutout'), ('Need to Install', 'Need to Install'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='main_db_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='main_supply_from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='material_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='meter_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='no_of_sets',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='obstacle_building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='obstacle_electric_pole',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='obstacle_mobile_tower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='obstacle_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='obstacle_other_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='panels_in_one_row',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='project_category',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='purpose',
            field=models.CharField(blank=True, choices=[('On-Grid', 'On-Grid'), ('Off-Grid', 'Off-Grid'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='roof_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='roof_direction',
            field=models.CharField(blank=True, choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='roof_tilt_angle',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='sanction_load_kw',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='shadow_afternoon_from',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='shadow_afternoon_percent',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='shadow_afternoon_to',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='shadow_analysis_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='shadow_evening_from',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='shadow_evening_percent',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='shadow_evening_to',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='shadow_morning_from',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='shadow_morning_percent',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='shadow_morning_to',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='site_drawing',
            field=models.ImageField(blank=True, null=True, upload_to='site_survey_drawings/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), malwa_solar.validators.validate_upload_size]),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='structure_type',
            field=models.CharField(blank=True, choices=[('GP', 'GP'), ('GL', 'GL'), ('CGL', 'CGL'), ('ZM', 'ZM')], max_length=10),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='supply_voltage',
            field=models.CharField(blank=True, choices=[('Single Phase', 'Single Phase'), ('Three Phase', 'Three Phase')], max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='survey_engineer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='survey_engineer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='tariff_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesurveyphoto',
            name='slot',
            field=models.CharField(choices=[('North Side', 'North Side'), ('South Side', 'South Side'), ('East Side', 'East Side'), ('West Side', 'West Side'), ('Overall Roof', 'Overall Roof'), ('Roof Close-up', 'Roof Close-up'), ('Water Tank', 'Water Tank'), ('Obstacle', 'Obstacle'), ('Drone Photo', 'Drone Photo'), ('Earthing Location', 'Earthing Location'), ('Inverter Location', 'Inverter Location'), ('Meter', 'Meter'), ('Cable Route', 'Cable Route'), ('Front View', 'Front View'), ('Roof View', 'Roof View'), ('Main DB Photo', 'Main DB Photo'), ('Consumer Bill', 'Consumer Bill'), ('Shadow Area Photo', 'Shadow Area Photo'), ('GPS Location', 'GPS Location')], max_length=30),
        ),
    ]
