# Generated by Django 4.2.30 on 2026-07-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_sitesurvey_client_form_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesurveyphoto',
            name='slot',
            field=models.CharField(choices=[('North Side', 'North Side'), ('South Side', 'South Side'), ('East Side', 'East Side'), ('West Side', 'West Side'), ('Overall Roof', 'Overall Roof'), ('Roof Close-up', 'Roof Close-up'), ('Water Tank', 'Water Tank'), ('Obstacle', 'Obstacle'), ('Drone Photo', 'Drone Photo'), ('Earthing Location', 'Earthing Location'), ('Inverter Location', 'Inverter Location'), ('Meter', 'Meter'), ('Cable Route', 'Cable Route'), ('Front View', 'Front View'), ('Roof View', 'Roof View'), ('Main DB Photo', 'Main DB Photo'), ('Consumer Bill', 'Consumer Bill'), ('Shadow Area Photo', 'Shadow Area Photo'), ('GPS Location', 'GPS Location'), ('Site Drawing', 'Site Drawing')], max_length=30),
        ),
    ]
