# Generated by Django 4.2.30 on 2026-08-29 08:10

import django.core.validators
from django.db import migrations, models
import malwa_solar.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_materialplan_inventory_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialplan',
            name='planning_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='projectapprovaldocument',
            name='file',
            field=models.FileField(upload_to='approval_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'mp4', 'mov', 'webm', 'm4v']), malwa_solar.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(upload_to='project_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'mp4', 'mov', 'webm', 'm4v']), malwa_solar.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='projectexpensedocument',
            name='file',
            field=models.FileField(upload_to='expense_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'mp4', 'mov', 'webm', 'm4v']), malwa_solar.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='sitesurvey',
            name='meter_phase',
            field=models.CharField(blank=True, choices=[('Normal Single Phase', 'Normal Single Phase'), ('Normal 3 Phase', 'Normal 3 Phase'), ('Smart Single Phase', 'Smart Single Phase'), ('Smart 3 Phase', 'Smart 3 Phase'), ('Normal LTCT', 'Normal LTCT'), ('Smart LTCT', 'Smart LTCT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesurvey',
            name='module_orientation',
            field=models.CharField(blank=True, choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape'), ('Both', 'Both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesurvey',
            name='roof_direction',
            field=models.CharField(blank=True, choices=[('South', 'South'), ('South-East', 'South-East'), ('South-West', 'South-West')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesurvey',
            name='roof_type',
            field=models.CharField(blank=True, choices=[('RBC Roof', 'RBC Roof'), ('Ground Mount', 'Ground Mount')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesurvey',
            name='structure_type',
            field=models.CharField(blank=True, choices=[('GP', 'GP'), ('GL', 'GL'), ('HDGI', 'HDGI'), ('ZM', 'ZM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesurvey',
            name='supply_voltage',
            field=models.CharField(blank=True, choices=[('Normal Single Phase', 'Normal Single Phase'), ('Normal 3 Phase', 'Normal 3 Phase'), ('Smart Single Phase', 'Smart Single Phase'), ('Smart 3 Phase', 'Smart 3 Phase'), ('Normal LTCT', 'Normal LTCT'), ('Smart LTCT', 'Smart LTCT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesurveyphoto',
            name='slot',
            field=models.CharField(choices=[('South Side', 'South Side'), ('South-East Side', 'South-East Side'), ('South-West Side', 'South-West Side'), ('Front View', 'Front View'), ('Inverter Location Photo', 'Inverter Location Photo'), ('Meter Photo Close to Main DB', 'Meter Photo Close to Main DB'), ('Earthing Location Photo', 'Earthing Location Photo'), ('Conduiting Photo 1', 'Conduiting Photo 1'), ('Conduiting Photo 2', 'Conduiting Photo 2'), ('Conduiting Photo 3', 'Conduiting Photo 3'), ('Conduiting Photo 4', 'Conduiting Photo 4'), ('Conduiting Photo 5', 'Conduiting Photo 5'), ('Conduiting Photo 6', 'Conduiting Photo 6'), ('Conduiting Photo 7', 'Conduiting Photo 7'), ('Conduiting Photo 8', 'Conduiting Photo 8'), ('Site Drawing 1', 'Site Drawing 1'), ('Site Drawing 2', 'Site Drawing 2'), ('Site Drawing 3', 'Site Drawing 3'), ('Site Drawing 4', 'Site Drawing 4')], max_length=30),
        ),
        migrations.AlterField(
            model_name='subsidydocument',
            name='file',
            field=models.FileField(upload_to='subsidy_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'mp4', 'mov', 'webm', 'm4v']), malwa_solar.validators.validate_upload_size]),
        ),
    ]
