# Generated by Django 4.2.30 on 2026-09-29 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0026_financial_interop_category_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_sheet_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('items', models.JSONField(blank=True, default=list)),
                ('extra_items', models.JSONField(blank=True, default=list)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('work_orders_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_sheets', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_sheet', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
