# Generated by Django 4.2.30 on 2026-10-02 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0029_pending_flow_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Site Survey', 'Site Survey'), ('Quotation', 'Quotation'), ('Material Planning', 'Material Planning'), ('Job Sheet', 'Job Sheet'), ('Dispatch', 'Dispatch'), ('Installation', 'Installation'), ('Sales Challan', 'Sales Challan'), ('Invoice', 'Invoice'), ('Completed', 'Completed')], default='Site Survey', max_length=30)),
                ('history', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pm_stage_tracker', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_stage_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
