# Generated by Django 4.2.30 on 2026-10-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_project_pipeline_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesurvey',
            name='inverter_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='inverter_capacity_kw',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='inverter_quantity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='inverter_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='meter_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='panel_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='panel_count',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='panel_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='panel_wattage_w',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesurveyphoto',
            name='slot',
            field=models.CharField(choices=[('South Side', 'South Side'), ('South-East Side', 'South-East Side'), ('South-West Side', 'South-West Side'), ('Front View', 'Front View'), ('Panel Placement Photo', 'Panel Placement Photo'), ('Inverter Location Photo', 'Inverter Location Photo'), ('Meter Photo Close to Main DB', 'Meter Photo Close to Main DB'), ('Earthing Location Photo', 'Earthing Location Photo'), ('Conduiting Photo 1', 'Conduiting Photo 1'), ('Conduiting Photo 2', 'Conduiting Photo 2'), ('Conduiting Photo 3', 'Conduiting Photo 3'), ('Conduiting Photo 4', 'Conduiting Photo 4'), ('Conduiting Photo 5', 'Conduiting Photo 5'), ('Conduiting Photo 6', 'Conduiting Photo 6'), ('Conduiting Photo 7', 'Conduiting Photo 7'), ('Conduiting Photo 8', 'Conduiting Photo 8'), ('Site Drawing 1', 'Site Drawing 1'), ('Site Drawing 2', 'Site Drawing 2'), ('Site Drawing 3', 'Site Drawing 3'), ('Site Drawing 4', 'Site Drawing 4')], max_length=30),
        ),
    ]
