services:
  - type: web
    name: malwa-solar-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn malwa_solar.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --worker-class gthread --threads 4
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: malwa_solar.settings.production
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: solar-crm-frontend-0vcw.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://solar-crm-frontend-bay.vercel.app,https://solar-crm-frontend-1gv4z1tdr-sheddy-smiths-projects.vercel.app,http://localhost:5173
      - key: CSRF_TRUSTED_ORIGINS
        value: https://solar-crm-frontend-0vcw.onrender.com,https://solar-crm-frontend-bay.vercel.app,https://solar-crm-frontend-1gv4z1tdr-sheddy-smiths-projects.vercel.app
