# Generated by Django 4.2.30 on 2026-10-02 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('om', '0006_om_status_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, db_index=True, max_length=40)),
                ('category', models.CharField(choices=[('Service', 'Service'), ('Ticket', 'Ticket'), ('Insurance', 'Insurance'), ('Task', 'Task'), ('Free Service', 'Free Service'), ('General', 'General')], db_index=True, default='General', max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('upcoming', 'Upcoming'), ('info', 'Info')], db_index=True, default='info', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('channel', models.CharField(choices=[('crm', 'CRM'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='crm', max_length=10)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='om.omplant')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
