# Generated by Django 4.2.30 on 2026-10-02 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_pending_flow_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liaisoning', '0003_alter_liaisondocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaisondocument',
            name='doc_type',
            field=models.CharField(choices=[('Aadhaar Card', 'Aadhaar Card'), ('PAN Card', 'PAN Card'), ('Electricity Bill', 'Electricity Bill'), ('Property Document', 'Property Document'), ('Bank Passbook', 'Bank Passbook'), ('Site Photo', 'Site Photo'), ('Application Form', 'Application Form'), ('Approval Letter', 'Approval Letter'), ('Agreement', 'Agreement'), ('Inspection Report', 'Inspection Report'), ('Net Meter Certificate', 'Net Meter Certificate'), ('Commissioning Report', 'Commissioning Report'), ('Compliance Certificate', 'Compliance Certificate'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='liaisondocument',
            name='module',
            field=models.CharField(choices=[('General', 'General'), ('Application', 'Application'), ('Approval', 'Approval'), ('Agreement', 'Agreement'), ('Inspection', 'Inspection'), ('Net Meter', 'Net Meter'), ('Commissioning', 'Commissioning'), ('Compliance', 'Compliance')], default='General', max_length=20),
        ),
        migrations.CreateModel(
            name='LiaisonProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Documents', 'Documents'), ('Application', 'Application'), ('Agreement', 'Agreement'), ('Inspection', 'Inspection'), ('Net Meter', 'Net Meter'), ('Commissioning', 'Commissioning'), ('Subsidy', 'Subsidy'), ('Completed', 'Completed')], default='Documents', max_length=20)),
                ('history', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liaison_stage', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lc_stage_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiaisonNetMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(choices=[('Bi-directional Meter', 'Bi-directional Meter'), ('Net Meter', 'Net Meter'), ('Solar Generation Meter', 'Solar Generation Meter'), ('Other', 'Other')], default='Bi-directional Meter', max_length=30)),
                ('meter_number', models.CharField(blank=True, max_length=100)),
                ('meter_make', models.CharField(blank=True, max_length=100)),
                ('phase', models.CharField(blank=True, choices=[('Single Phase', 'Single Phase'), ('Three Phase', 'Three Phase')], max_length=20)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Testing', 'Testing'), ('Installed', 'Installed'), ('Rejected', 'Rejected')], default='Applied', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lc_net_meters_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lc_net_meters', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiaisonAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('Net Metering Agreement', 'Net Metering Agreement'), ('Power Purchase Agreement', 'Power Purchase Agreement'), ('DISCOM Connection Agreement', 'DISCOM Connection Agreement'), ('Customer Agreement', 'Customer Agreement'), ('Other', 'Other')], default='Net Metering Agreement', max_length=50)),
                ('agreement_number', models.CharField(blank=True, max_length=100)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('signed_by', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Signed', 'Signed'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lc_agreements_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lc_agreements', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
