# Generated by Django 4.2.30 on 2026-07-10 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_options_and_more'),
        ('om', '0002_alter_omdocument_file_alter_omreport_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='omsparepart',
            name='linked_inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_spare_parts', to='inventory.inventoryitem'),
        ),
    ]
