# Generated by Django 4.2.30 on 2026-10-02 12:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import malwa_solar.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amc', '0003_alter_amcdocument_file'),
        ('inventory', '0007_inventorycategory_form_designer'),
        ('projects', '0031_site_survey_panel_inverter_meter'),
        ('accounts_module', '0017_remove_project_expense_vouchers'),
        ('leads', '0021_unassign_tele_sales_assignees'),
        ('om', '0004_alter_omdocument_file_alter_omreport_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('alternate_mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('customer_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Institutional', 'Institutional'), ('Other', 'Other')], default='Residential', max_length=20)),
                ('plant_name', models.CharField(max_length=200)),
                ('plant_location', models.CharField(blank=True, max_length=255)),
                ('capacity_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plant_type', models.CharField(blank=True, max_length=100)),
                ('system_type', models.CharField(choices=[('On Grid', 'On Grid'), ('Hybrid', 'Hybrid'), ('Off Grid', 'Off Grid')], default='On Grid', max_length=20)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('handover_date', models.DateField(blank=True, null=True)),
                ('panel_brand', models.CharField(blank=True, max_length=100)),
                ('panel_model', models.CharField(blank=True, max_length=100)),
                ('panel_wattage_w', models.CharField(blank=True, max_length=20)),
                ('panel_count', models.CharField(blank=True, max_length=20)),
                ('panel_serials', models.TextField(blank=True)),
                ('inverter_brand', models.CharField(blank=True, max_length=100)),
                ('inverter_model', models.CharField(blank=True, max_length=100)),
                ('inverter_capacity_kw', models.CharField(blank=True, max_length=20)),
                ('inverter_serial', models.CharField(blank=True, max_length=200)),
                ('structure_type', models.CharField(blank=True, max_length=100)),
                ('acdb_details', models.CharField(blank=True, max_length=255)),
                ('dcdb_details', models.CharField(blank=True, max_length=255)),
                ('earthing_details', models.TextField(blank=True)),
                ('net_meter_details', models.TextField(blank=True)),
                ('warranty_details', models.TextField(blank=True)),
                ('free_service_start', models.DateField(blank=True, null=True)),
                ('free_service_end', models.DateField(blank=True, null=True)),
                ('om_status', models.CharField(choices=[('Free Service Active', 'Free Service Active'), ('Free Service Expiring Soon', 'Free Service Expiring Soon'), ('Free Service Expired', 'Free Service Expired'), ('Paid O&M', 'Paid O&M'), ('AMC Active', 'AMC Active'), ('AMC Expired', 'AMC Expired')], db_index=True, default='Free Service Active', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amc_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_plants', to='amc.amccontract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_plants_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_plants', to='accounts_module.account')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_plants', to='leads.lead')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='om_plant', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ombreakdownticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ombreakdownticket',
            name='complaint_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ombreakdownticket',
            name='complaint_type',
            field=models.CharField(blank=True, choices=[('Inverter Error', 'Inverter Error'), ('Low Generation', 'Low Generation'), ('No Generation', 'No Generation'), ('Panel Damage', 'Panel Damage'), ('Panel Cleaning', 'Panel Cleaning'), ('Wiring / Cable', 'Wiring / Cable'), ('Earthing', 'Earthing'), ('Meter / Net Meter', 'Meter / Net Meter'), ('Structure', 'Structure'), ('Monitoring / App', 'Monitoring / App'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='ombreakdownticket',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ombreakdownticket',
            name='expected_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ombreakdownticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omdocument',
            name='category',
            field=models.CharField(choices=[('Before', 'Before'), ('After', 'After'), ('Policy', 'Policy'), ('General', 'General')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='ommaintenancetask',
            name='assigned_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ommaintenancetask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ommaintenancetask',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ommaintenancetask',
            name='sequence_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ommaintenancetask',
            name='source',
            field=models.CharField(choices=[('Quarterly', 'Quarterly'), ('Ticket', 'Ticket'), ('Manual', 'Manual')], db_index=True, default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='ommaintenancetask',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='om.ombreakdownticket'),
        ),
        migrations.AddField(
            model_name='ommaintenancetask',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='assigned_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_visits_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='customer_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='customer_signature',
            field=models.ImageField(blank=True, null=True, upload_to='om_signatures/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), malwa_solar.validators.validate_upload_size]),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='engineer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='fault_found',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='final_status',
            field=models.CharField(blank=True, choices=[('Resolved', 'Resolved'), ('Partially Resolved', 'Partially Resolved'), ('Pending Parts', 'Pending Parts'), ('Revisit Required', 'Revisit Required')], max_length=30),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='inspection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='labour_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='plant_generation_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='service_type',
            field=models.CharField(choices=[('Quarterly', 'Quarterly'), ('Complaint', 'Complaint'), ('Emergency', 'Emergency'), ('Inspection', 'Inspection'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='om.ommaintenancetask'),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='om.ombreakdownticket'),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='work_done',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ombreakdownticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='ombreakdownticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Site Visit', 'Site Visit'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='omdocument',
            name='module',
            field=models.CharField(choices=[('Maintenance', 'Maintenance'), ('Ticket', 'Ticket'), ('Visit', 'Visit'), ('Asset', 'Asset'), ('SparePart', 'SparePart'), ('Plant', 'Plant'), ('Insurance', 'Insurance'), ('General', 'General')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='ommaintenancetask',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='ommaintenancetask',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OmVisitPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('MC4 Connector', 'MC4 Connector'), ('DC Fuse', 'DC Fuse'), ('AC Fuse', 'AC Fuse'), ('MCB', 'MCB'), ('MCCB', 'MCCB'), ('Cable', 'Cable'), ('SPD', 'SPD'), ('Fan', 'Fan'), ('Inverter Card', 'Inverter Card'), ('Connector', 'Connector'), ('Other', 'Other')], default='Other', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('used_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_visit_parts', to='inventory.inventoryitem')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_used', to='om.omplant')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_used', to='om.ombreakdownticket')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_parts_used', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='om.omsitevisit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OmInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Insured', 'Insured'), ('Not Insured', 'Not Insured'), ('Expired', 'Expired')], db_index=True, default='Insured', max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('policy_type', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(choices=[('1 Year', '1 Year'), ('2 Year', '2 Year'), ('3 Year', '3 Year'), ('5 Year', '5 Year'), ('Custom', 'Custom')], default='1 Year', max_length=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('policy_document', models.FileField(blank=True, null=True, upload_to='om_insurance/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'mp4', 'mov', 'webm', 'm4v']), malwa_solar.validators.validate_upload_size])),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_insurances_created', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='om.omplant')),
            ],
            options={
                'ordering': ['-expiry_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ombreakdownticket',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='om.omplant'),
        ),
        migrations.AddField(
            model_name='omdocument',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='om.omplant'),
        ),
        migrations.AddField(
            model_name='ommaintenancetask',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='om.omplant'),
        ),
        migrations.AddField(
            model_name='omsitevisit',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='om.omplant'),
        ),
    ]
