# Generated by Django 4.2.30 on 2026-07-10 06:20

import django.core.validators
from django.db import migrations, models
import malwa_solar.validators


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amcdocument',
            name='file',
            field=models.FileField(blank=True, upload_to='amc/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx']), malwa_solar.validators.validate_upload_size]),
        ),
    ]
