# Generated by Django 4.2.30 on 2026-09-01 11:01

import django.core.validators
from django.db import migrations, models
import malwa_solar.validators


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_alter_amcdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amcdocument',
            name='file',
            field=models.FileField(blank=True, upload_to='amc/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'mp4', 'mov', 'webm', 'm4v']), malwa_solar.validators.validate_upload_size]),
        ),
    ]
