# Generated by Django 4.2.30 on 2026-06-22 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('Dashboard', 'Dashboard'), ('Leads', 'Leads'), ('Follow-ups', 'Follow-ups'), ('IVRS Management', 'IVRS Management'), ('Approvals', 'Approvals'), ('Project Management', 'Project Management'), ('Liaisoning & Commissioning', 'Liaisoning & Commissioning'), ('O&M', 'O&M'), ('Accounts', 'Accounts'), ('Reports', 'Reports'), ('User Management', 'User Management'), ('Settings', 'Settings')], max_length=40)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_import', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('full_access', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Users'},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'mobile'], name='accounts_us_email_a5896a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['mobile'], name='accounts_us_mobile_646276_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('mobile', ''), ('mobile__regex', '^\\d{10}$'), _connector='OR'), name='mobile_length_or_blank'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'mobile'), name='unique_email_mobile_pair'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.role'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'module')},
        ),
    ]
