# Generated by Django 4.2.30 on 2026-07-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rolepermission_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('Dashboard', 'Dashboard'), ('Leads', 'Leads'), ('Follow-ups', 'Follow-ups'), ('IVRS Management', 'IVRS Management'), ('Approvals', 'Approvals'), ('Project Management', 'Project Management'), ('Liaisoning & Commissioning', 'Liaisoning & Commissioning'), ('O&M', 'O&M'), ('Accounts', 'Accounts'), ('Inventory', 'Inventory'), ('AMC & Warranty', 'AMC & Warranty'), ('Reports', 'Reports'), ('User Management', 'User Management'), ('Settings', 'Settings')], max_length=40),
        ),
    ]
