# Generated by Django 4.2.30 on 2026-07-10 06:45
# Hand-edited: convert existing blank ('') mobile values to NULL *between*
# making the column nullable and adding unique=True (BUG-072). Postgres
# treats '' as a real, non-distinct value under a unique constraint/index
# (unlike NULL, which is always distinct from every other NULL) — applying
# unique=True while more than one row still has mobile='' would fail the
# migration outright. The column also isn't nullable yet at the DB level
# (only `blank=True`, not `null=True`, previously), so NULLing out any row
# has to happen only after the column itself is altered to allow NULL.

from django.db import migrations, models


def blank_mobile_to_null(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(mobile='').update(mobile=None)


def null_mobile_to_blank(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(mobile__isnull=True).update(mobile='')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_workforce_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.RunPython(blank_mobile_to_null, null_mobile_to_blank),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
