# Generated by Django 4.2.30 on 2026-09-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_seed_vendors_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='typing_transliteration',
            field=models.BooleanField(default=True),
        ),
    ]
