# Generated by Django 4.2.30 on 2026-06-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='latitude',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='longitude',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='project_type',
            field=models.CharField(blank=True, choices=[('On-Grid', 'On-Grid'), ('Off-Grid', 'Off-Grid'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='requirement_details',
            field=models.TextField(blank=True),
        ),
    ]
