# Generated by Django 4.2.30 on 2026-06-17 09:32

import apps.leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_alternate_number_lead_email_lead_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='ivrs_number',
            field=models.CharField(blank=True, default=apps.leads.models.generate_ivrs, max_length=50, unique=True),
        ),
    ]
