# Generated by Django 4.2.30 on 2026-06-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_adminapproval_request_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'ordering': ['id'], 'verbose_name_plural': 'Quotation Items'},
        ),
        migrations.AlterUniqueTogether(
            name='quotationitem',
            unique_together={('quotation', 'item_name')},
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__regex', '^\\d+(\\.\\d+)?$')), name='quantity_numeric'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 0)), name='rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='amount_non_negative'),
        ),
    ]
