# Generated by Django 4.2.30 on 2026-06-22 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0005_alter_quotationitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='ac_cable',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='acdb',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='advance_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='commissioning_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='connectors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='dc_cable',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='dcdb',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discom_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='earthing_kit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='quotation',
            name='estimated_annual_generation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='exclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='foundation_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='installation_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='installation_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='installation_type',
            field=models.CharField(blank=True, choices=[('Rooftop', 'Rooftop'), ('Ground Mounted', 'Ground Mounted'), ('Elevated Structure', 'Elevated Structure')], max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_warranty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='liaisoning_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lightning_arrester',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='material_dispatch_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='module_orientation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='monthly_electricity_bill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='net_metering_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='number_of_panels',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='panel_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='panel_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='panel_warranty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='panel_wattage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='plant_capacity_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Residential Subsidy', 'Residential Subsidy'), ('Residential Non Subsidy', 'Residential Non Subsidy'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Agriculture', 'Agriculture')], max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sanctioned_load_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='scope_of_work',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='shadow_free_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_material',
            field=models.CharField(blank=True, choices=[('GI', 'GI'), ('HDGI', 'HDGI'), ('Aluminium', 'Aluminium')], max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_warranty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subsidy_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subsidy_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='template',
            field=models.CharField(choices=[('Residential Subsidy', 'Residential Subsidy Solar Quotation'), ('Residential Non-Subsidy', 'Residential Non-Subsidy Quotation'), ('Commercial', 'Commercial Solar Quotation'), ('Industrial', 'Industrial Solar Quotation'), ('Structure', 'Solar Structure Quotation'), ('BOS Kit', 'BOS Kit Quotation')], default='Residential Subsidy', max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_dc_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='transportation_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='wind_speed_rating',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='workmanship_warranty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
