# Generated by Django 4.2.30 on 2026-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_quotation_ac_cable_quotation_acdb_quotation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cable_tray',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='connection_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='consumer_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='existing_meter_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='fasteners',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='mc4_connector',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='panel_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='pvc_pipe',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='specification',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
