# Generated by Django 4.2.30 on 2026-06-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_quotation_aadhaar_number_quotation_cable_tray_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='coating_details',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='execution_timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
