# Generated by Django 4.2.30 on 2026-07-07 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0008_quotation_coating_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSiteSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_address', models.TextField(blank=True)),
                ('latitude', models.CharField(blank=True, max_length=20)),
                ('longitude', models.CharField(blank=True, max_length=20)),
                ('mounting_type', models.CharField(blank=True, choices=[('Ground Mount', 'Ground Mount'), ('Roof / Terrace Mount', 'Roof / Terrace Mount'), ('Tin Shed Mount', 'Tin Shed Mount')], max_length=30)),
                ('site_size_sqft', models.CharField(blank=True, max_length=50)),
                ('customer_feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20)),
                ('survey_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_survey', to='leads.lead')),
                ('surveyed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_site_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSurveyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lead_survey_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='leads.leadsitesurvey')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_survey_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
