# Generated by Django 4.2.30 on 2026-07-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_leadsitesurvey_leadsurveyphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsitesurvey',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20),
        ),
    ]
