# Generated by Django 4.2.30 on 2026-07-08 07:07

import apps.leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_leadsitesurvey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsurveyphoto',
            name='image',
            field=models.ImageField(upload_to=apps.leads.models.lead_survey_photo_upload_path),
        ),
    ]
