# Generated by Django 4.2.30 on 2026-07-10 06:20

import apps.leads.models
import django.core.validators
from django.db import migrations, models
import malwa_solar.validators


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_leadsurveyphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsurveyphoto',
            name='image',
            field=models.ImageField(upload_to=apps.leads.models.lead_survey_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), malwa_solar.validators.validate_upload_size]),
        ),
    ]
