# Generated by Django 4.2.30 on 2026-07-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_leadsequencecounter_adminapproval_created_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='reminder',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='followup',
            name='status_after',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
