# Generated by Django 4.2.30 on 2026-07-18 11:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_followup_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='annual_saving_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cleaning_solution_including',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='govt_liasoning_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst_18_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst_5_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='infra_items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lt_panel_including',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='monthly_production_units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='net_meter_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='net_metering_including',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms_text',
            field=models.TextField(blank=True, default='Payment terms 50% advance, 30% after structure deliver & 20% after plant installed'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='plant_life_years',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_cost_with_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_spec_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subject',
            field=models.CharField(blank=True, default='Comprehensive proposal for grid tied', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tariff_rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('7.50'), max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='taxable_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tilt_angle_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='use_split_gst',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='validity_text',
            field=models.CharField(blank=True, default='Quotation validity is till availability of material/10 days', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='walkway_including',
            field=models.BooleanField(default=True),
        ),
    ]
