# Generated by Django 4.2.30 on 2026-07-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0004_alter_employeeattendance_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeIdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('Installation', 'Installation'), ('Engineering', 'Engineering'), ('Electrical', 'Electrical'), ('Sales', 'Sales'), ('Quality', 'Quality'), ('Logistics', 'Logistics'), ('HSE', 'HSE'), ('Operations', 'Operations'), ('Administration', 'Administration'), ('Other', 'Other')], max_length=100),
        ),
    ]
