# Generated by Django 4.2.30 on 2026-07-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_employeeidcounter_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
