# Generated by Django 4.2.30 on 2026-09-01 11:01

import django.core.validators
from django.db import migrations, models
import malwa_solar.validators


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0008_employee_duty_hours_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to='workforce/docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'mp4', 'mov', 'webm', 'm4v']), malwa_solar.validators.validate_upload_size]),
        ),
    ]
