# Generated by Django 4.2.30 on 2026-06-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-created_at'], 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_number__isnull', False)), fields=('transaction_date', 'reference_number'), name='unique_transaction_reference'),
        ),
    ]
