# Generated by Django 4.2.30 on 2026-07-03 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_add_project_approval'),
        ('accounts_module', '0003_account_bankaccount_cheque_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cheque',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_record', to='accounts_module.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_payments', to='projects.project'),
        ),
        migrations.AddField(
            model_name='payment',
            name='project_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_payment', to='projects.projectpayment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry', to='accounts_module.payment'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: _copy_balance_to_opening(apps),
            migrations.RunPython.noop,
        ),
    ]


def _copy_balance_to_opening(apps):
    Account = apps.get_model('accounts_module', 'Account')
    BankAccount = apps.get_model('accounts_module', 'BankAccount')
    for row in Account.objects.all():
        row.opening_balance = row.balance
        row.save(update_fields=['opening_balance'])
    for row in BankAccount.objects.all():
        row.opening_balance = row.balance
        row.save(update_fields=['opening_balance'])
