# Generated by Django 4.2.30 on 2026-07-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0005_accounts_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchasechallan',
            name='challan_no',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sellchallan',
            name='challan_no',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
