# Generated by Django 4.2.30 on 2026-07-10 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_options_and_more'),
        ('workforce', '0005_employeeidcounter_alter_employee_department'),
        ('accounts_module', '0006_alter_paymentvoucher_voucher_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='employee_voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_payment_voucher', to='workforce.employeevoucher'),
        ),
        migrations.AddField(
            model_name='purchasechallanline',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_challan_lines', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='purchasechallanline',
            name='stock_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_challan_line', to='inventory.stockmovement'),
        ),
    ]
