# Generated by Django 4.2.30 on 2026-08-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_financial_interop_category_map'),
        ('accounts_module', '0007_purchasechallanline_stock_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='material_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_voucher', to='projects.materialplan'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='project_expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_voucher', to='projects.projectexpense'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_payment_voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry', to='accounts_module.paymentvoucher'),
        ),
        migrations.CreateModel(
            name='AccountCategoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_module', models.CharField(choices=[('Material', 'Material'), ('Labour', 'Labour'), ('Transport', 'Transport'), ('Subcontractor', 'Subcontractor'), ('ProjectExpense', 'Project Expense'), ('PlanningDifference', 'Material Planning Difference'), ('Revenue', 'Revenue'), ('Other', 'Other')], max_length=40)),
                ('business_category', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_maps', to='accounts_module.chartofaccount')),
            ],
            options={
                'verbose_name': 'Category → COA Map',
                'verbose_name_plural': 'Category → COA Maps',
                'ordering': ['business_module', 'business_category'],
                'unique_together': {('business_module', 'business_category')},
            },
        ),
    ]
