# Generated by Django 4.2.30 on 2026-09-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0014_paymentvoucher_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellchallan',
            name='source',
            field=models.CharField(choices=[('Accounts', 'Accounts'), ('Project', 'Project')], default='Accounts', max_length=20),
        ),
        migrations.AddField(
            model_name='sellinvoice',
            name='source',
            field=models.CharField(choices=[('Accounts', 'Accounts'), ('Project', 'Project')], default='Accounts', max_length=20),
        ),
    ]
