# Generated by Django 4.2.30 on 2026-09-29 09:54

from django.db import migrations, models


def backfill_subtotal(apps, schema_editor):
    SellChallan = apps.get_model('accounts_module', 'SellChallan')
    SellChallan.objects.filter(subtotal=0).update(subtotal=models.F('total_amount'))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0015_sell_document_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellchallan',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='sellchallan',
            name='gst_mode',
            field=models.CharField(choices=[('None', 'No GST'), ('Split', 'Solar Split (70% @5% + 30% @18%)'), ('Flat', 'Flat %')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='sellchallan',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sellchallan',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sellchallan',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sellchallan',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='sellchallanline',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellchallanline',
            name='section',
            field=models.CharField(choices=[('Main', 'Main'), ('Additional', 'Additional Work')], default='Main', max_length=12),
        ),
        migrations.AddField(
            model_name='sellchallanline',
            name='specification',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.RunPython(backfill_subtotal, migrations.RunPython.noop),
    ]
